### ISSUE TITLE
jQuery & bootstrap-custom.min.js not loading

### ISSUE THREAD

**Issue by kchez** [mhanney/twitter-bootstrap-customization#1]
Console shows errors for the two javascript files referenced in the `src/index.html` file.
```
<script src="lib/jquery/jquery.js"></script>
<script src="dist/bootstrap-custom.min.js"></script>
```

1. The `lib/jquery/jquery.js` path doesn't seem to be correct in relation to the `public/` folder, which is where the page is being served from.

   

2. As for the second script not loading
The `dist/bootstrap-custom.min.js` path includes a `dist/` directory, but this is not included anywhere in the `gruntfile.js` file.
__Fixed__ -  Changed the `src/index.html` script path to:
    ```
    <script src="./bootstrap-custom.min.js"></script>
    ```
_(Note the inclusion of the relative path to the current directory: `./` &mdash; it won't work without it)_

**Comment by mhanney** [comment]
Thanks. Pushed an update.
